// Generated types from Supabase - run `npm run db:generate` to update
// This is a placeholder until you connect to your Supabase project

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
	public: {
		Tables: {
			// Alias for performer_profiles (common query pattern)
			performers: {
				Row: {
					id: string;
					user_id: string;
					stage_name: string | null;
					bio: string | null;
					tagline: string | null;
					location_name: string;
					location_lat: number | null;
					location_lng: number | null;
					travel_radius_miles: number;
					performer_category: string[];
					act_types: string[];
					min_rate_pence: number | null;
					hourly_rate_pence: number | null;
					event_rate_pence: number | null;
					show_rate_pence: number | null;
					stripe_account_id: string | null;
					stripe_onboarding_complete: boolean;
					is_verified: boolean;
					verification_badges: string[];
					avg_rating: number;
					total_reviews: number;
					total_bookings: number;
					response_rate: number;
					response_time_hours: number | null;
					is_active: boolean;
					is_featured: boolean;
					profile_complete: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					stage_name?: string | null;
					bio?: string | null;
					tagline?: string | null;
					location_name: string;
					location_lat?: number | null;
					location_lng?: number | null;
					travel_radius_miles?: number;
					performer_category: string[];
					act_types: string[];
					min_rate_pence?: number | null;
					hourly_rate_pence?: number | null;
					event_rate_pence?: number | null;
					show_rate_pence?: number | null;
					stripe_account_id?: string | null;
					stripe_onboarding_complete?: boolean;
					is_verified?: boolean;
					verification_badges?: string[];
					avg_rating?: number;
					total_reviews?: number;
					total_bookings?: number;
					response_rate?: number;
					response_time_hours?: number | null;
					is_active?: boolean;
					is_featured?: boolean;
					profile_complete?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					stage_name?: string | null;
					bio?: string | null;
					tagline?: string | null;
					location_name?: string;
					location_lat?: number | null;
					location_lng?: number | null;
					travel_radius_miles?: number;
					performer_category?: string[];
					act_types?: string[];
					min_rate_pence?: number | null;
					hourly_rate_pence?: number | null;
					event_rate_pence?: number | null;
					show_rate_pence?: number | null;
					stripe_account_id?: string | null;
					stripe_onboarding_complete?: boolean;
					is_verified?: boolean;
					verification_badges?: string[];
					avg_rating?: number;
					total_reviews?: number;
					total_bookings?: number;
					response_rate?: number;
					response_time_hours?: number | null;
					is_active?: boolean;
					is_featured?: boolean;
					profile_complete?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			users: {
				Row: {
					id: string;
					email: string;
					full_name: string;
					avatar_url: string | null;
					phone: string | null;
					user_type: 'performer' | 'client' | 'both';
					email_verified: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					email: string;
					full_name: string;
					avatar_url?: string | null;
					phone?: string | null;
					user_type?: 'performer' | 'client' | 'both';
					email_verified?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					email?: string;
					full_name?: string;
					avatar_url?: string | null;
					phone?: string | null;
					user_type?: 'performer' | 'client' | 'both';
					email_verified?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			performer_profiles: {
				Row: {
					id: string;
					user_id: string;
					stage_name: string | null;
					bio: string | null;
					tagline: string | null;
					location_name: string;
					location_lat: number | null;
					location_lng: number | null;
					travel_radius_miles: number;
					performer_category: string[];
					act_types: string[];
					min_rate_pence: number | null;
					hourly_rate_pence: number | null;
					event_rate_pence: number | null;
					show_rate_pence: number | null;
					stripe_account_id: string | null;
					stripe_onboarding_complete: boolean;
					is_verified: boolean;
					verification_badges: string[];
					avg_rating: number;
					total_reviews: number;
					total_bookings: number;
					response_rate: number;
					response_time_hours: number | null;
					is_active: boolean;
					is_featured: boolean;
					profile_complete: boolean;
					vouch_count: number;
					community_trusted: boolean;
					verification_tier: 'community' | 'insured' | 'verified_pro';
					equity_member_id: string | null;
					equity_verified: boolean;
					equity_verified_at: string | null;
					pli_document_url: string | null;
					pli_expiry_date: string | null;
					pli_verified: boolean;
					pli_verified_at: string | null;
					pli_provider: string | null;
					pli_policy_number: string | null;
					cancellation_policy: 'flexible' | 'standard' | 'strict';
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					stage_name?: string | null;
					bio?: string | null;
					tagline?: string | null;
					location_name: string;
					location_lat?: number | null;
					location_lng?: number | null;
					travel_radius_miles?: number;
					performer_category: string[];
					act_types: string[];
					min_rate_pence?: number | null;
					hourly_rate_pence?: number | null;
					event_rate_pence?: number | null;
					show_rate_pence?: number | null;
					stripe_account_id?: string | null;
					stripe_onboarding_complete?: boolean;
					is_verified?: boolean;
					verification_badges?: string[];
					avg_rating?: number;
					total_reviews?: number;
					total_bookings?: number;
					response_rate?: number;
					response_time_hours?: number | null;
					is_active?: boolean;
					is_featured?: boolean;
					profile_complete?: boolean;
					vouch_count?: number;
					community_trusted?: boolean;
					verification_tier?: 'community' | 'insured' | 'verified_pro';
					equity_member_id?: string | null;
					equity_verified?: boolean;
					equity_verified_at?: string | null;
					pli_document_url?: string | null;
					pli_expiry_date?: string | null;
					pli_verified?: boolean;
					pli_verified_at?: string | null;
					pli_provider?: string | null;
					pli_policy_number?: string | null;
					cancellation_policy?: 'flexible' | 'standard' | 'strict';
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					stage_name?: string | null;
					bio?: string | null;
					tagline?: string | null;
					location_name?: string;
					location_lat?: number | null;
					location_lng?: number | null;
					travel_radius_miles?: number;
					performer_category?: string[];
					act_types?: string[];
					min_rate_pence?: number | null;
					hourly_rate_pence?: number | null;
					event_rate_pence?: number | null;
					show_rate_pence?: number | null;
					stripe_account_id?: string | null;
					stripe_onboarding_complete?: boolean;
					is_verified?: boolean;
					verification_badges?: string[];
					avg_rating?: number;
					total_reviews?: number;
					total_bookings?: number;
					response_rate?: number;
					response_time_hours?: number | null;
					is_active?: boolean;
					is_featured?: boolean;
					profile_complete?: boolean;
					vouch_count?: number;
					community_trusted?: boolean;
					verification_tier?: 'community' | 'insured' | 'verified_pro';
					equity_member_id?: string | null;
					equity_verified?: boolean;
					equity_verified_at?: string | null;
					pli_document_url?: string | null;
					pli_expiry_date?: string | null;
					pli_verified?: boolean;
					pli_verified_at?: string | null;
					pli_provider?: string | null;
					pli_policy_number?: string | null;
					cancellation_policy?: 'flexible' | 'standard' | 'strict';
					created_at?: string;
					updated_at?: string;
				};
			};
			performer_media: {
				Row: {
					id: string;
					performer_id: string;
					media_type: 'video' | 'photo';
					url: string;
					thumbnail_url: string | null;
					cloudinary_public_id: string | null;
					title: string | null;
					description: string | null;
					is_primary: boolean;
					sort_order: number;
					duration_seconds: number | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					performer_id: string;
					media_type: 'video' | 'photo';
					url: string;
					thumbnail_url?: string | null;
					cloudinary_public_id?: string | null;
					title?: string | null;
					description?: string | null;
					is_primary?: boolean;
					sort_order?: number;
					duration_seconds?: number | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					performer_id?: string;
					media_type?: 'video' | 'photo';
					url?: string;
					thumbnail_url?: string | null;
					cloudinary_public_id?: string | null;
					title?: string | null;
					description?: string | null;
					is_primary?: boolean;
					sort_order?: number;
					duration_seconds?: number | null;
					created_at?: string;
				};
			};
			bookings: {
				Row: {
					id: string;
					performer_id: string;
					client_id: string;
					status: 'inquiry' | 'pending' | 'accepted' | 'confirmed' | 'completed' | 'cancelled' | 'declined' | 'disputed';
					event_date: string;
					event_time: string | null;
					event_end_time: string | null;
					event_duration_hours: number | null;
					event_location: string;
					event_location_lat: number | null;
					event_location_lng: number | null;
					event_type: string | null;
					event_details: string | null;
					guest_count: number | null;
					quoted_price_pence: number;
					agreed_price_pence: number | null;
					deposit_pence: number | null;
					platform_fee_pence: number | null;
					performer_payout_pence: number | null;
					deposit_paid: boolean;
					deposit_paid_at: string | null;
					final_paid: boolean;
					final_paid_at: string | null;
					stripe_payment_intent_id: string | null;
					stripe_transfer_id: string | null;
					cancellation_policy: 'flexible' | 'standard' | 'strict';
					refund_amount_pence: number | null;
					refund_processed: boolean;
					refund_processed_at: string | null;
					created_at: string;
					updated_at: string;
					responded_at: string | null;
					completed_at: string | null;
				};
				Insert: {
					id?: string;
					performer_id: string;
					client_id: string;
					status?: 'inquiry' | 'pending' | 'accepted' | 'confirmed' | 'completed' | 'cancelled' | 'declined' | 'disputed';
					event_date: string;
					event_time?: string | null;
					event_end_time?: string | null;
					event_duration_hours?: number | null;
					event_location: string;
					event_location_lat?: number | null;
					event_location_lng?: number | null;
					event_type?: string | null;
					event_details?: string | null;
					guest_count?: number | null;
					quoted_price_pence: number;
					agreed_price_pence?: number | null;
					deposit_pence?: number | null;
					platform_fee_pence?: number | null;
					performer_payout_pence?: number | null;
					deposit_paid?: boolean;
					deposit_paid_at?: string | null;
					final_paid?: boolean;
					final_paid_at?: string | null;
					stripe_payment_intent_id?: string | null;
					stripe_transfer_id?: string | null;
					cancellation_policy?: 'flexible' | 'standard' | 'strict';
					refund_amount_pence?: number | null;
					refund_processed?: boolean;
					refund_processed_at?: string | null;
					created_at?: string;
					updated_at?: string;
					responded_at?: string | null;
					completed_at?: string | null;
				};
				Update: {
					id?: string;
					performer_id?: string;
					client_id?: string;
					status?: 'inquiry' | 'pending' | 'accepted' | 'confirmed' | 'completed' | 'cancelled' | 'declined' | 'disputed';
					event_date?: string;
					event_time?: string | null;
					event_end_time?: string | null;
					event_duration_hours?: number | null;
					event_location?: string;
					event_location_lat?: number | null;
					event_location_lng?: number | null;
					event_type?: string | null;
					event_details?: string | null;
					guest_count?: number | null;
					quoted_price_pence?: number;
					agreed_price_pence?: number | null;
					deposit_pence?: number | null;
					platform_fee_pence?: number | null;
					performer_payout_pence?: number | null;
					deposit_paid?: boolean;
					deposit_paid_at?: string | null;
					final_paid?: boolean;
					final_paid_at?: string | null;
					stripe_payment_intent_id?: string | null;
					stripe_transfer_id?: string | null;
					cancellation_policy?: 'flexible' | 'standard' | 'strict';
					refund_amount_pence?: number | null;
					refund_processed?: boolean;
					refund_processed_at?: string | null;
					created_at?: string;
					updated_at?: string;
					responded_at?: string | null;
					completed_at?: string | null;
				};
			};
			reviews: {
				Row: {
					id: string;
					booking_id: string;
					reviewer_id: string;
					reviewee_id: string;
					reviewer_type: 'client' | 'performer';
					rating: number;
					content: string | null;
					professionalism_rating: number | null;
					communication_rating: number | null;
					value_rating: number | null;
					is_public: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					booking_id: string;
					reviewer_id: string;
					reviewee_id: string;
					reviewer_type: 'client' | 'performer';
					rating: number;
					content?: string | null;
					professionalism_rating?: number | null;
					communication_rating?: number | null;
					value_rating?: number | null;
					is_public?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					booking_id?: string;
					reviewer_id?: string;
					reviewee_id?: string;
					reviewer_type?: 'client' | 'performer';
					rating?: number;
					content?: string | null;
					professionalism_rating?: number | null;
					communication_rating?: number | null;
					value_rating?: number | null;
					is_public?: boolean;
					created_at?: string;
				};
			};
			messages: {
				Row: {
					id: string;
					booking_id: string;
					sender_id: string;
					content: string;
					read_at: string | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					booking_id: string;
					sender_id: string;
					content: string;
					read_at?: string | null;
					created_at?: string;
				};
				Update: {
					id?: string;
					booking_id?: string;
					sender_id?: string;
					content?: string;
					read_at?: string | null;
					created_at?: string;
				};
			};
			availability: {
				Row: {
					id: string;
					performer_id: string;
					date: string;
					is_available: boolean;
					is_booked: boolean;
					notes: string | null;
				};
				Insert: {
					id?: string;
					performer_id: string;
					date: string;
					is_available?: boolean;
					is_booked?: boolean;
					notes?: string | null;
				};
				Update: {
					id?: string;
					performer_id?: string;
					date?: string;
					is_available?: boolean;
					is_booked?: boolean;
					notes?: string | null;
				};
			};
			performer_vouches: {
				Row: {
					id: string;
					voucher_id: string;
					vouchee_id: string;
					message: string | null;
					vouch_type: 'skill' | 'professionalism' | 'safety' | 'reliability';
					created_at: string;
				};
				Insert: {
					id?: string;
					voucher_id: string;
					vouchee_id: string;
					message?: string | null;
					vouch_type?: 'skill' | 'professionalism' | 'safety' | 'reliability';
					created_at?: string;
				};
				Update: {
					id?: string;
					voucher_id?: string;
					vouchee_id?: string;
					message?: string | null;
					vouch_type?: 'skill' | 'professionalism' | 'safety' | 'reliability';
					created_at?: string;
				};
			};
			booking_contracts: {
				Row: {
					id: string;
					booking_id: string;
					contract_text: string;
					contract_version: number;
					performer_signed: boolean;
					performer_signed_at: string | null;
					performer_ip: string | null;
					client_signed: boolean;
					client_signed_at: string | null;
					client_ip: string | null;
					status: 'draft' | 'pending' | 'signed' | 'voided';
					cancellation_terms: string | null;
					payment_terms: string | null;
					special_terms: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					booking_id: string;
					contract_text: string;
					contract_version?: number;
					performer_signed?: boolean;
					performer_signed_at?: string | null;
					performer_ip?: string | null;
					client_signed?: boolean;
					client_signed_at?: string | null;
					client_ip?: string | null;
					status?: 'draft' | 'pending' | 'signed' | 'voided';
					cancellation_terms?: string | null;
					payment_terms?: string | null;
					special_terms?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					booking_id?: string;
					contract_text?: string;
					contract_version?: number;
					performer_signed?: boolean;
					performer_signed_at?: string | null;
					performer_ip?: string | null;
					client_signed?: boolean;
					client_signed_at?: string | null;
					client_ip?: string | null;
					status?: 'draft' | 'pending' | 'signed' | 'voided';
					cancellation_terms?: string | null;
					payment_terms?: string | null;
					special_terms?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			blog_posts: {
				Row: {
					id: string;
					author_id: string;
					title: string;
					slug: string;
					content: string;
					excerpt: string | null;
					cover_image_url: string | null;
					category: 'tips' | 'safety' | 'business' | 'technique' | 'gear' | 'industry' | 'events' | 'community';
					tags: string[];
					status: 'draft' | 'published' | 'archived';
					published_at: string | null;
					view_count: number;
					like_count: number;
					is_featured: boolean;
					is_approved: boolean;
					moderated_at: string | null;
					moderated_by: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					author_id: string;
					title: string;
					slug: string;
					content: string;
					excerpt?: string | null;
					cover_image_url?: string | null;
					category?: 'tips' | 'safety' | 'business' | 'technique' | 'gear' | 'industry' | 'events' | 'community';
					tags?: string[];
					status?: 'draft' | 'published' | 'archived';
					published_at?: string | null;
					view_count?: number;
					like_count?: number;
					is_featured?: boolean;
					is_approved?: boolean;
					moderated_at?: string | null;
					moderated_by?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					author_id?: string;
					title?: string;
					slug?: string;
					content?: string;
					excerpt?: string | null;
					cover_image_url?: string | null;
					category?: 'tips' | 'safety' | 'business' | 'technique' | 'gear' | 'industry' | 'events' | 'community';
					tags?: string[];
					status?: 'draft' | 'published' | 'archived';
					published_at?: string | null;
					view_count?: number;
					like_count?: number;
					is_featured?: boolean;
					is_approved?: boolean;
					moderated_at?: string | null;
					moderated_by?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			blog_comments: {
				Row: {
					id: string;
					post_id: string;
					author_id: string;
					parent_id: string | null;
					content: string;
					is_approved: boolean;
					is_flagged: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					post_id: string;
					author_id: string;
					parent_id?: string | null;
					content: string;
					is_approved?: boolean;
					is_flagged?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					post_id?: string;
					author_id?: string;
					parent_id?: string | null;
					content?: string;
					is_approved?: boolean;
					is_flagged?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			notification_preferences: {
				Row: {
					id: string;
					user_id: string;
					email_booking_requests: boolean;
					email_booking_updates: boolean;
					email_messages: boolean;
					email_reviews: boolean;
					email_blog_comments: boolean;
					email_marketing: boolean;
					email_pli_expiry: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					email_booking_requests?: boolean;
					email_booking_updates?: boolean;
					email_messages?: boolean;
					email_reviews?: boolean;
					email_blog_comments?: boolean;
					email_marketing?: boolean;
					email_pli_expiry?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					email_booking_requests?: boolean;
					email_booking_updates?: boolean;
					email_messages?: boolean;
					email_reviews?: boolean;
					email_blog_comments?: boolean;
					email_marketing?: boolean;
					email_pli_expiry?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			notifications: {
				Row: {
					id: string;
					user_id: string;
					type: 'booking_request' | 'booking_update' | 'message' | 'review' | 'dispute' | 'system' | 'payment';
					title: string;
					body: string;
					link: string | null;
					read: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					type: 'booking_request' | 'booking_update' | 'message' | 'review' | 'dispute' | 'system' | 'payment';
					title: string;
					body: string;
					link?: string | null;
					read?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					type?: 'booking_request' | 'booking_update' | 'message' | 'review' | 'dispute' | 'system' | 'payment';
					title?: string;
					body?: string;
					link?: string | null;
					read?: boolean;
					created_at?: string;
				};
			};
			disputes: {
				Row: {
					id: string;
					booking_id: string;
					raised_by: string;
					raised_against: string;
					reason: string;
					description: string;
					evidence_urls: string[];
					status: 'open' | 'under_review' | 'resolved_refund' | 'resolved_warning' | 'resolved_no_action' | 'closed';
					admin_notes: string | null;
					resolution: string | null;
					refund_amount_pence: number | null;
					resolved_by: string | null;
					resolved_at: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					booking_id: string;
					raised_by: string;
					raised_against: string;
					reason: string;
					description: string;
					evidence_urls?: string[];
					status?: 'open' | 'under_review' | 'resolved_refund' | 'resolved_warning' | 'resolved_no_action' | 'closed';
					admin_notes?: string | null;
					resolution?: string | null;
					refund_amount_pence?: number | null;
					resolved_by?: string | null;
					resolved_at?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					booking_id?: string;
					raised_by?: string;
					raised_against?: string;
					reason?: string;
					description?: string;
					evidence_urls?: string[];
					status?: 'open' | 'under_review' | 'resolved_refund' | 'resolved_warning' | 'resolved_no_action' | 'closed';
					admin_notes?: string | null;
					resolution?: string | null;
					refund_amount_pence?: number | null;
					resolved_by?: string | null;
					resolved_at?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
		};
		Views: {};
		Functions: {};
		Enums: {};
	};
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// Convenience types
export type User = Tables<'users'>;
export type Performer = Tables<'performers'>;
export type PerformerProfile = Tables<'performer_profiles'>;
export type PerformerMedia = Tables<'performer_media'>;
export type Booking = Tables<'bookings'>;
export type Review = Tables<'reviews'>;
export type Message = Tables<'messages'>;
export type Availability = Tables<'availability'>;
export type PerformerVouch = Tables<'performer_vouches'>;
export type BookingContract = Tables<'booking_contracts'>;
export type BlogPost = Tables<'blog_posts'>;
export type BlogComment = Tables<'blog_comments'>;
export type NotificationPreference = Tables<'notification_preferences'>;
export type Notification = Tables<'notifications'>;
export type Dispute = Tables<'disputes'>;

// Vouch type with voucher details (from get_performer_vouches function)
export interface VouchWithVoucher {
	id: string;
	voucher_id: string;
	voucher_stage_name: string | null;
	voucher_avatar_url: string | null;
	voucher_user_id: string;
	message: string | null;
	vouch_type: 'skill' | 'professionalism' | 'safety' | 'reliability';
	created_at: string;
}
